<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="43" started-at="2022-02-18T04:19:49 YAKT" finished-at="2022-02-18T04:19:49 YAKT">
    <groups>
    </groups>
    <test name="Test" duration-ms="43" started-at="2022-02-18T04:19:49 YAKT" finished-at="2022-02-18T04:19:49 YAKT">
      <class name="online_tusur.unit_online_tusur.GetAgeTest">
        <test-method status="PASS" signature="testNG_getAge(int,online_tusur.unit_online_tusur.Student)[pri:0, instance:online_tusur.unit_online_tusur.GetAgeTest@c46bcd4, instance params:[]]" name="testNG_getAge" duration-ms="2" started-at="2022-02-18T04:19:49 YAKT" data-provider="ageProvider" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[online_tusur.unit_online_tusur.Student@1efee8e7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNG_getAge -->
        <test-method status="FAIL" signature="testNG_getAge(int,online_tusur.unit_online_tusur.Student)[pri:0, instance:online_tusur.unit_online_tusur.GetAgeTest@c46bcd4, instance params:[]]" name="testNG_getAge" duration-ms="1" started-at="2022-02-18T04:19:49 YAKT" data-provider="ageProvider" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[online_tusur.unit_online_tusur.Student@6cc7b4de]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [18] but found [50]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at online_tusur.unit_online_tusur.GetAgeTest.testNG_getAge(StudentTestNGDynam.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNG_getAge -->
      </class> <!-- online_tusur.unit_online_tusur.GetAgeTest -->
      <class name="online_tusur.unit_online_tusur.GetFirstNameTest">
        <test-method status="PASS" signature="testNG_getFirstName(java.lang.String,online_tusur.unit_online_tusur.Student)[pri:0, instance:online_tusur.unit_online_tusur.GetFirstNameTest@631330c, instance params:[]]" name="testNG_getFirstName" duration-ms="1" started-at="2022-02-18T04:19:49 YAKT" data-provider="firstNameProvider" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ivan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[online_tusur.unit_online_tusur.Student@799d4f69]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNG_getFirstName -->
        <test-method status="FAIL" signature="testNG_getFirstName(java.lang.String,online_tusur.unit_online_tusur.Student)[pri:0, instance:online_tusur.unit_online_tusur.GetFirstNameTest@631330c, instance params:[]]" name="testNG_getFirstName" duration-ms="0" started-at="2022-02-18T04:19:49 YAKT" data-provider="firstNameProvider" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Alla-Victoria]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[online_tusur.unit_online_tusur.Student@290dbf45]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Alla-victoria] but found [Alla-Victoria]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Alla-victoria] but found [Alla-Victoria]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at online_tusur.unit_online_tusur.GetFirstNameTest.testNG_getFirstName(StudentTestNGDynam.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNG_getFirstName -->
      </class> <!-- online_tusur.unit_online_tusur.GetFirstNameTest -->
      <class name="online_tusur.unit_online_tusur.StudentTestNGParam">
        <test-method status="PASS" signature="TestNG_AgeAvg(int,java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.StudentTestNGParam@2a742aa2]" name="TestNG_AgeAvg" duration-ms="6" started-at="2022-02-18T04:19:49 YAKT" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[23]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Иван Иванов 20,Семен Семенов 30,Алла-Виктория Петрова 19]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNG_AgeAvg -->
      </class> <!-- online_tusur.unit_online_tusur.StudentTestNGParam -->
      <class name="online_tusur.unit_online_tusur.GetLastNameTest">
        <test-method status="PASS" signature="testNG_getLastName(java.lang.String,online_tusur.unit_online_tusur.Student)[pri:0, instance:online_tusur.unit_online_tusur.GetLastNameTest@42f93a98, instance params:[]]" name="testNG_getLastName" duration-ms="1" started-at="2022-02-18T04:19:49 YAKT" data-provider="lastNameProvider" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ivanov]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[online_tusur.unit_online_tusur.Student@2d127a61]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNG_getLastName -->
        <test-method status="FAIL" signature="testNG_getLastName(java.lang.String,online_tusur.unit_online_tusur.Student)[pri:0, instance:online_tusur.unit_online_tusur.GetLastNameTest@42f93a98, instance params:[]]" name="testNG_getLastName" duration-ms="1" started-at="2022-02-18T04:19:49 YAKT" data-provider="lastNameProvider" finished-at="2022-02-18T04:19:49 YAKT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Petrova-Sergeeva]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[online_tusur.unit_online_tusur.Student@11c20519]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Petrova-sergeeva] but found [Petrova-Sergeeva]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Petrova-sergeeva] but found [Petrova-Sergeeva]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at online_tusur.unit_online_tusur.GetLastNameTest.testNG_getLastName(StudentTestNGDynam.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNG_getLastName -->
      </class> <!-- online_tusur.unit_online_tusur.GetLastNameTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
